// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCG7aHpEWpoIidZePidkiOX89yBYKDIHHU',
    appId: '1:316908780822:web:0f82d6ec2196fee5bf2437',
    messagingSenderId: '316908780822',
    projectId: 'taskmate-b7c44',
    authDomain: 'taskmate-b7c44.firebaseapp.com',
    storageBucket: 'taskmate-b7c44.appspot.com',
    measurementId: 'G-PSNH4JXYLB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0iTvoNDyrtoRjY9DCfxV4J-izLRQ5Vlk',
    appId: '1:316908780822:android:bd9f3cc29004fac2bf2437',
    messagingSenderId: '316908780822',
    projectId: 'taskmate-b7c44',
    storageBucket: 'taskmate-b7c44.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDghPpTvxLxHGChlo_mXFn1WY1kpg-lvV8',
    appId: '1:316908780822:ios:a07b673e95f4a4fcbf2437',
    messagingSenderId: '316908780822',
    projectId: 'taskmate-b7c44',
    storageBucket: 'taskmate-b7c44.appspot.com',
    androidClientId: '316908780822-88ncek0s0aq2hdsqu2cs1kc5vsd4e4d3.apps.googleusercontent.com',
    iosClientId: '316908780822-s5hdki6vqqhfjtb2llitusp0emdlider.apps.googleusercontent.com',
    iosBundleId: 'com.example.taskMate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDghPpTvxLxHGChlo_mXFn1WY1kpg-lvV8',
    appId: '1:316908780822:ios:ad850a054ca5fcf1bf2437',
    messagingSenderId: '316908780822',
    projectId: 'taskmate-b7c44',
    storageBucket: 'taskmate-b7c44.appspot.com',
    androidClientId: '316908780822-88ncek0s0aq2hdsqu2cs1kc5vsd4e4d3.apps.googleusercontent.com',
    iosClientId: '316908780822-2reueqeqvgf00o8b3t89q9kalbjle9e9.apps.googleusercontent.com',
    iosBundleId: 'com.example.taskMate.RunnerTests',
  );
}
